accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
]

either/urls.py
from django.contrib import admin
from django.urls import path, include
from questions import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('questions/', include('questions.urls')),
    path('accounts/', include('accounts.urls')),
    path('', views.index),
]

questions/urls.py
from django.urls import path
from . import views

app_name = "questions"

urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('<int:id>/', views.detail, name="detail"),
    path('<int:id>/update/', views.update, name="update"),
    path('<int:id>/delete/', views.delete, name="delete"),
    path('<int:id>/choices/create/', views.choice_create, name="choice_create"),
    path('<int:question_id>/choices/<int:choice_id>/delete', views.choice_delete, name="choice_delete"),
]

accounts/models.py
from django.db import models

# Create your models here.

questions/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    title = models.CharField(max_length=100)
    choice_1 = models.CharField(max_length=100)
    choice_2 = models.CharField(max_length=100)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    pick = models.IntegerField()
    comment= models.CharField(max_length=100)

questions/forms.py
from django import forms
from .models import Question, Choice

class QuestionsForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = "__all__"

class ChoiceForm(forms.ModelForm):
    choices = [(1, '왼쪽'), (2, '오른쪽')]
    pick = forms.ChoiceField(choices=choices, widget=forms.RadioSelect())
    class Meta:
        model = Choice
        fields = ('pick', 'comment', )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

# Create your views here.

def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('questions:index')
    else:
        form = UserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)

def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('questions:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'questions/form.html', context)

def logout(request):
    auth_logout(request)
    return redirect('questions:index')

questions/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import QuestionsForm, ChoiceForm
from .models import Question, Choice
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    questions = Question.objects.all()
    return render(request, 'questions/index.html', {'questions': questions})

def detail(request, id):
    question = get_object_or_404(Question, id=id)
    choice_form = ChoiceForm()
    # choice_1 = len(Choice.objects.filter(question=question, pick=1))
    # choice_2 = len(Choice.objects.filter(question=question, pick=2))
    # total = choice_1 + choice_2
    # per1 = round(choice_1/total)
    # per2 = round(choice_2/total)
    choices = question.choice_set.all()
    choice_1 = choices.filter(pick=1).count()
    choice_2 = len(choices.filter(pick=2))

    total = choices.count()

    per_1, per_2 = 50, 50
    if total != 0:
        per_1 = choice_1/total * 100
        per_2 = choice_2/total * 100

    context = {
        'question':question,
        'choice_form':choice_form,
        'num1': choice_1,
        'num2': choice_2,
        'per_1': per_1,
        'per_2': per_2, 
    }
    return render(request, 'questions/detail.html', context)

def update(request, id):
    question = get_object_or_404(Question, id=id)
    if request.method == "POST":
        form = QuestionsForm(request.POST, instance=question)
        if form.is_valid():
            form.save()
            return redirect('questions:detail', id)
    else:
        form = QuestionsForm(instance=question)
    context = {
        'form': form
    }
    return render(request, 'questions/form.html', context)

def delete(request, id):
    question = get_object_or_404(Question, id=id)
    question.delete()
    return redirect('questions:index')

@login_required
def create(request):
    # 1. 글쓰기 클릭 > GET요청
    # 6. 사용자가 올바르지않은 데이터를 입력하고 제출 클릭 > POST요청
    # 12. 사용자가 올바른 데이터를 입력하고 제출 클릭 > POST요청

    # 7. POST요청이기 때문에 if문 실행
    # 13. POST요청이기 때문에 if문 실행
    if request.method == "POST":
        # 8. 들어온 요청에 대한 form을 생성
        # 14. 들어온 요청에 대한 form을 생성
        form = QuestionsForm(request.POST)
        # 9. 생성된 form의 데이터가 올바른지 검증
        # 15. 생성된 form의 데이터가 올바른지 검증
        if form.is_valid():
            # 16. 데이터가 올바르기 때문에 저장
            form.save()
            # 17. 데이터 저장 후 메인페이지로 이동
            return redirect('questions:index')
    # 2. GET요청이기때문에 else문 실행
    else:
        # 3. 입력을 위한 form을 생성 (GET으로 요청받았을때)
        form = QuestionsForm()
    # 4. form을 context에 넣기
    # 10. form의 데이터가 검증을 통과 못했을 시
    #     올바르게 입력된 데이터는 남기고 다시 form 보여주기
    context = {
        'form': form
    }
    # 5. form.html 보여주기 (빈 form)
    # 11. form.html 보여주기 (올바른 데이터는 들어있음)
    return render(request, 'questions/form.html', context)

def choice_create(request, id):
    question = get_object_or_404(Question, id=id)
    if request.method == "POST":
        # form = ChoiceForm(request.POST, instance=question)
        # if form.is_valid():
        #     choice = Choice()
        #     pick = request.POST.get('pick')
        #     comment = request.POST.get('comment')
        #     choice.question = question
        #     choice.pick = pick
        #     choice.comment = comment
        #     choice.save()
        choice_form = ChoiceForm(request.POST)
        if choice_form.is_valid():
            choice = choice_form.save(commit=False)
            choice.question = question
            choice.save()
            return redirect('questions:detail', id)
    else:
        pass

@require_POST
def choice_delete(request, question_id, choice_id):
    choice = get_object_or_404(Choice, id=choice_id)
    if request.method == "POST":
        choice.delete()
    return redirect('questions:detail', question_id)

accounts/templates/accounts/form.html
{% extends 'questions/base.html' %}
{% load bootstrap4 %}
{% block body %}
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="가입" class="btn btn-primary">
  </form>
{% endblock %}

questions/templates/questions/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  {% bootstrap_css %}
</head>
<body>
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <!-- Brand -->
    <a class="navbar-brand" href="{% url 'questions:index' %}">Home</a>
  
    <!-- Links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'questions:create' %}">글쓰기</a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item">
          <a class="nav-link disabled">{{user}}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:signup' %}">SignUp</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
        </li>
      {% endif %}
    </ul>
  </nav>
  <div class="container mt-5">
    {% block body %}
    {% endblock %}
  </div>
  {% bootstrap_javascript jquery="full" %}
</body>
</html>

questions/templates/questions/detail.html
{% extends 'questions/base.html' %}
{% load bootstrap4 %}
{% block body %}
  <h1>DETAIL</h1>
  <div class="jumbotron bg-dark text-center text-white">
    <div class="row justify-content-between">
      <div>
        <h1 class="display-4">{{question.title}}</h1>
      </div>
      <div>
        <form action="{% url 'questions:update' question.id %}">
          <input type="submit" value="수정" class="btn btn-outline-warning">
        </form>
        <form class="mt-1" action="{% url 'questions:delete' question.id %}" method="POST">
          {% csrf_token %}
          <input type="submit" value="삭제" class="btn btn-outline-danger">
        </form>
      </div>
    </div>
    <hr class="my-4">
    <div class="progress my-3">
      <div class="progress-bar" role="progressbar" style="width: {{per_1}}%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100">{{per_1|floatformat}}%</div>
      <div class="progress-bar bg-danger" role="progressbar" style="width: {{per_2}}%" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100">{{per_2|floatformat}}%</div>
    </div>
    <form action="{% url 'questions:choice_create' question.id %}" method="POST">
      {% csrf_token %}
      <div class="btn-group btn-group-toggle w-100" data-toggle="buttons">
          <label class="btn btn-primary" style="width:{{per_1}}%">
            <input type="radio" name="pick" value="1">{{question.choice_1}} : {{num1}}
          </label>
          <label class="btn btn-danger" style="width:{{per_2}}%">
            <input type="radio" name="pick" value="2">{{question.choice_2}} : {{num2}}
          </label>
        </div>
      <input type="text" class="mt-3 form-control" placeholder="comment" name="comment">
      <input type="submit" class="mt-3 btn btn-outline-success w-100" value="PICK!">
    </form>
    <br>
    {% for choice in question.choice_set.all %}
      {% if choice.pick == 1%}
        <div class="row justify-content-start">
          <div class="row justify-content-between alert w-50 alert-primary">
            {{choice.comment}}
            <form action="{% url 'questions:choice_delete' question.id choice.id %}" method="POST">
              <input type="submit" class="btn btn-dark" value="삭제">
            </form>
          </div>
        </div>
      {% else %}
        <div class="row justify-content-end">
          <div class="row justify-content-between alert alert-danger w-50">
            <form action="{% url 'questions:choice_delete' question.id choice.id %}" method="POST">
                <input type="submit" class="btn btn-dark" value="삭제">
            </form>
            {{choice.comment}}
          </div>
        </div>
      {% endif %}
    {% endfor %}
  </div>
{% endblock %}

questions/templates/questions/form.html
{% extends 'questions/base.html' %}
{% load bootstrap4 %}
{% block body %}
  <h1>FORM</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input class="btn btn-primary" type="submit">
  </form>
{% endblock %}

questions/templates/questions/index.html
{% extends 'questions/base.html' %}
{% load bootstrap4 %}
{% block body %}
  <h1>INDEX</h1>
  <div class="jumbotron text-center">
    <h1 class="display-4">Question List</h1>
  {% for question in questions %}
    <a class="btn btn-primary w-100 my-3" href="{% url 'questions:detail' question.id %}">{{question.title}}</a>
  {% endfor %}
</div>
{% endblock %}